/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    "intro",
    {
      type: "category",
      label: "Getting Started",
      link: { type: "doc", id: "get-started/get-started" },
      items: ["get-started/hello-world", "get-started/nux-cli"],
    },
    "static-files",
    {
      type: "category",
      link: { type: "doc", id: "templating-engine/intro" },
      label: "Templating Engine",
      items: ["templating-engine/ejs"],
    },
    {
      type: "category",
      link: { type: "doc", id: "apps/intro" },
      label: "Apps",
      items: ["apps/create-an-app", "apps/mount-an-app"],
    },
    {
      type: "category",
      link: { type: "doc", id: "deployment/intro" },
      label: "Deployment",
      items: [],
    },
  ],
};

module.exports = sidebars;
